<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Cart extends CI_Controller {
	public function add($productId) {
		//$this->load->model('CartModel');
		//$this->CartModel->add($productId);			
		$this->load->model('Sunglasses');
		$this->Sunglasses->addToCart($productId);

		echo 'cart count: '.$this->cart->total_items();
	}
	public function remove($rowid) { // rowid is item's "cart" id, generated by cart class 

		//$this->load->model('CartModel');
		//$this->CartModel->add($productId);			
		$this->load->model('Sunglasses');
		$this->Sunglasses->removeFromCart($rowid);

		echo 'cart count: '.$this->cart->total_items();
	}
	/** view method
	 * Loads cart view, showing all the products.
	 */
	public function view() {
		$this->load->view('cart.php');	
	}
}
