<?php
class Sunglasses extends CI_Model {
	function __construct() {
		parent::__construct();
	}
	

	public function selectAll() {
		$sql = "SELECT * FROM sunglasses";
		$query = $this->db->query($sql);

		return $query->result_array();
	}

	public function selectById($id) {
		$sql = "SELECT * FROM sunglasses WHERE id=".$id;
		$query = $this->db->query($sql);

		return $query->row_array();
	}

	public function addToCart($id) {
		$sunglasses = $this->selectById($id);		
		$sunglasses['qty'] = 1;
		$sunglasses['name'] = 'sunglasses'; // name is required by cart library

		$this->cart->insert($sunglasses);
	}

	public function removeFromCart($rowid) { // rowid is item's "cart" id, generated by cart class 
		$product = $this->cart->findByRowid($rowid);
		$product['qty']--;

		$data = array(
			'rowid' => $rowid,
			'qty' => 0
		);
		$this->cart->update($product);
	}


}
